### PR TITLE
Add Geojson examples and tests

### PR DESCRIPTION
**Pull request by jyucsiro**
This PR adds GeoJSON examples and some tests via pytests

### CODE REVIEW

**Comment by jyucsiro** [comment]
@bellie888 Could you review this PR please? 

This adds some functionality in `call_DGGS.py` to allow Shapely objects to be used for calling the dggs engine from a workflow reading geojson test_data files. 

Currently 2 main sets of tests: MultiPolygon/Polygon and MultiLineString/LineString objects. 

from the root repo dir, run the following:
```
$ pytests tests/enablement/test_geojson_to_dggs.py
```

**Comment by bellie888** [comment]
Hi, is this the code you are talking about?
test_shp_to_dggs_enablement.py
looks like it  - actually it has nothing to do with geojson

with respect to 'shapely'  - it doesn't carry any attributes with it at all
"shapefile" comes from the pyshp module and carries all the table attributes. See
https://pypi.org/project/pyshp/

quite happy if we want to do everything in geojson (if possible)
geojson keeps everything together


Also "call_DGGS.py" is very old.
The scripts in the "enablement_tagging" are more up-to-date and don't use shapely.
You probably need "polygon_DGGS_enablement.py" from that folder in the repo
Cheers
Joe
PS I will try running that pytest after lunch :)

**Comment by bellie888** [comment]
Notes from testing:
1. shapefile doesn't need to be in utils - it is now part of a common module called pyshp 
2. but hoping to remove shapefile and just use geojson - to simplify and empower the code
3. Mostly I have the DGGS (AusPIX) in the first column because it is like a key in a database table.

Actually I'm not sure what you are trying to do? There might be some confusion on my part.
Do you want to:
1. import the shapefile SA1_ACT_2016
2. then DGGS enable it
3. then test is "one of the output lines has a certain DGGS cell" = R7852335255

there is a much better way to write it - we don't need all the w.field stuff
actually the code doesn't work I think.

How about I write the code with the test
The test is just looking for that one cell in the output, if it finds it - it passes?

Cheers
Joe

**Comment by bellie888** [comment]
actually I haven't found the geojson one yet
                   ie tests/enablement/test_geojson_to_dggs.py
it's not in the main repo  GeoscienceAustralia/AusPIX_DGGS

Oh, I just found your scripts under the links at the top of this page (above)
There are heaps of stuff there - give me time to have a look

**Comment by bellie888** [comment]
@jyucsiro
Hi Jonathan, I'm having a good look at it today. Using geojson for input and geojson/csv for output can automate the whole process easily. The user will receive their attributes (properties) back with DGGS cell joined.

**Comment by jyucsiro** [comment]
Hi @bellie888 - thanks for atking a look. 

The intent of this PR is to introduce some tests to begin showing how to input some geojson and interacting with existing code in the repo (i.e. working with the `callablemodules` submodule) to perform the enablement. Example geojson is included in `test_data` so that we can consistently perform tests with tests defined in `tests/enablement/*`. I've had to propose some updates to `call_DGGS.py` to get things working. 

A question I had was whether `call_DGGS.py` is the right place for the functionality to be called or elsewhere? My assumption was that `call_DGGS.py` would be a good place to start.

The examples cover MultiPolygon and MultiLineString data at the moment.

**Comment by bellie888** [comment]
@jyucsiro 
no the module "call_DGGS" is very old and clunky.

we have been using "dggs_in_poly" - which uses the pyShp 'shapefile' module - this has been working on some really big datasets and very complicated polygons with holes and things in them. I couldn't get "shapely" to handle holes in polygons at the time. The test could apply to this "dggs_in_poly"  module.

I am interested in using the functionality of geojson and pygeoj - and have almost converted over to a version that inputs and outputs in geojson. The test could apply to this as well. This version reads in a geojson with lots of polys in it, finds the cells for each poly, then exports back out as geojson or csv.  I think this can be fully automated, maintaining the attribute properties while adding AusPIX cells for the user. It will have more rows that the source file because it is broken into cells.

the is a folder on git called "enablement_tagging" an has scripts for points, lines and poygons as fairly recent examples
https://github.com/GeoscienceAustralia/AusPIX_DGGS

thoughts?
Cheers
Joe

**Comment by jyucsiro** [comment]
Ok - so we don't want to use `call_DGGS.py`. 
https://github.com/GeoscienceAustralia/AusPIX_DGGS/blob/master/auspixdggs/callablemodules/call_DGGS.py

But we want to use `dggs_in_poly.py`?
https://github.com/GeoscienceAustralia/AusPIX_DGGS/blob/master/auspixdggs/callablemodules/dggs_in_poly.py

The scripts in `enablement_tagging` have some good examples. These need to be turned into callable modules as part of the packaging in the `callablemodules` directory.
https://github.com/GeoscienceAustralia/AusPIX_DGGS/tree/master/auspixdggs/callablemodules

Where should the relevant functions go? In a single file for each function or a single file for multiple functions? I'm leaning towards the latter...

**Comment by bellie888** [comment]
I have sort of taken "dggs_in_poly" and incorporated it into dggy_in_poly_for_geojson (a new file)
Maybe you are happy to work with that? cause I have thrown all functions in there at the moment so it's an encapsulated unit (except for AusPIX engine).
This script now finds the cells in the polys we give it.

Still working issues:  multipart polygons, and need to check polygons with holes.

I'll push the new file up to Git - to the enablement tagging folder by 3.00 pm
It includes the essential parts of "dggy_in_poly.py" too

maybe I should clean up that callable-modules folder so there is less confusion
Cheers
Joe

**Comment by bellie888** [comment]
I can do similar for points and lines too, but away on hols next week.
Just let me know the structure so it can be used in the API that Jevy is working on :)

**Comment by jyucsiro** [comment]
what about moving the functions you are using in the *.py files in `enablement_tagging` to `callablemodules` so that it can be reused as part of the package?

Jevy's API code is expecting the functions to be in `callablemodules` (or `utils`) so if it's outside of that folder, then his API can't call it because of the way the python package is defined.

**Comment by jyucsiro** [comment]
Replaced with #11

**Pull request closed without merging**
